version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - $DB_PORT:$DB_PORT_DOCKER
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
  
  server:
    depends_on:
      - mysqldb
    build: ./server
    restart: unless-stopped
    env_file: ./server/.env.development
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_PORT_DOCKER
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - backend
      - frontend

  client:
    depends_on:
      - server
    build:
      context: ./client
      args:
        - REACT_APP_API_BASE_URL=http://127.0.0.1:6868/
    ports:
      - 3000:3000
    networks:
      - frontend  

volumes: 
  db:

networks:
  backend:
  frontend: